export const groupId = GROUP_ID
export const accessToken = 'vk1.a.IAAQH35XAEpXUmOZGUaY9cVQHYV5ybNPneGWYsSAqeTv6HCn-vnYfuAlZ2ZI_YRD0IwRRNQRlquGadhkwmQVGJHzopNIpc81b5vI8kFEHNNP9SRMlf9PW2mjEaY3LIXAcmfM54HXHzDBeHYzVXxA7EgKELeKaWUrlDoE0lhyKI-7J3dx2wtyBkvVa3ekSzdCtwHjhcqE7RfvjYBPo2u2YQ'
export const version = '5.131'

